language: cpp

compiler:
  - clang

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y
  - sudo apt-get update -qq
  - sudo apt-get install qt55base qt55websockets
  - mkdir build
  - cd build
  - cmake ../

script: 
  - source /opt/qt55/bin/qt55-env.sh
  - make
