language: cpp

compiler:
  - clang

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo add-apt-repository ppa:zarquon42/precise-backports -y
  - sudo apt-get-repository ppa:rebuntu16/avogadro+unofficial -y
  - sudo apt-get update -qq
  - sudo apt-get install libvtk6-dev libboost-all-dev libeigen3-dev
  - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
  - sudo apt-get install qt5-default qttools5-dev-tools
  - mkdir build
  - cd build
  - cmake ../

script: make
